name: "Main Workflow"
#on: ["push", "pull_request"]
on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # https://github.com/dominikh/staticcheck-action
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: WillAbides/setup-go-faster@v1.8.0
      with:
        go-version: 1.18.x
    - name: go vet
      run: |
        go vet ./...
    - name: go test
      run: |
        go test ./... -coverprofile coverage.out
        go tool cover -func coverage.out
    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2022.1.3"
        install-go: false
        #cache-key: ${{ matrix.go }}
        cache-key: 1.18.x
    # https://github.com/Jerome1337/gofmt-action
    - uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: '.'
        gofmt-flags: '-l -d'
