name: size-label
on: pull_request
permissions:
  pull-requests: write
jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
    - name: size-label
      uses: "pascalgn/size-label-action@v0.4.3"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
